#!/bin/bash -l

rm *.out *.xml *.log

MOLPRO=/home/quantura/molpro/bin/molpro
NUM_OMP_THREADS=20
MEM=1000

echo Molpro Path: $MOLPRO
echo Number of OMP threads: $NUM_OMP_THREADS
echo Memory: $MEM m

export OMP_THREAD_LIMIT=$NUM_OMP_THREADS

for i in `find -iname input`;
do 
	place=`echo $i | sed "s/\/input//g"`
	cd $place
       	pwd
	$MOLPRO -t $NUM_OMP_THREADS -m $MEM --no-xml-output < input > output 
	cd -
done
